### PR TITLE
interface{} -> any

### PR DESCRIPTION
**Pull request by flowchartsman**

### CODE REVIEW

**Comment by flowchartsman** [comment]
Sorry in advance, @breml 😬

**Comment by breml** [comment]
See my comment in https://github.com/mna/pigeon/pull/108#issuecomment-1466934638

**Comment by flowchartsman** [comment]
😉

**Comment by flowchartsman** [comment]
Might need a bit more towards the codegen side to make it work everywhere, but I believe this would take care of it as a backport.

**Review by breml — APPROVED** [review]
LGTM

**Pull request merged**
