### PR TITLE
Fix duplicate function code generation

### LINKED ISSUE #65: Build failure only when --optimize-grammar is set
Hello,

When building a particular grammar generated with `--optimize-grammar`, it may result in build failures. The same grammar builds correctly when this option is not set. I know this flag is documented as "experimental", but still, this is probably fixable.

I have tried to reduce the grammar to the minimum required to reproduce the issue, and the result is in the github repo https://github.com/mna/pigeon-bug-optimize-grammar .

The grammar looks like this:

```
Start <- List         // NOTE: changing List to X here makes the bug disappear
List <- X ( ',' X )*  // NOTE: changing X to Y here makes the bug disappear
X <- 'X' Y?           // NOTE: removing the "?" makes the bug disappear
Y <- 'Y'
  {
    // NOTE: code block required for the bug, gets rendered twice with --optimize-grammar
    return nil, nil
  }
```

And with the `--optimize-grammar` option set, the output of `go build` (`go1.10.2` on macOS for me) is:

```
bug/grammar.go:43:22: (*parser).callonList4 undefined (type *parser has no method callonList4)
bug/grammar.go:94:6: (*current).onList10 redeclared in this block
	previous declaration at bug/grammar.go:82:6
bug/grammar.go:100:6: (*parser).callonList10 redeclared in this block
	previous declaration at bug/grammar.go:88:6
```

I'll investigate and see if I can find a fix and send a PR, but I wanted to open the issue first in case you have ideas on what may cause this.

Thanks!
Martin

### PR DESCRIPTION
**Pull request by mna**
This closes #65 .

After optimization with `--optimize-grammar`, a single action (or other code-block-associated expression)  AST node can be used in more than one location. As a result, it gets assigned conflicting `FuncIx` values and, because the builder first generates the grammar AST tree and then generates the code block, the functions get generated more than once with the same name, resulting in build failures on the generated code.

This PR makes sure that a given AST node never gets its `FuncIx` overwritten (avoiding the `(*parser).callonList4 undefined` type of errors for the initial `FuncIx` that was subsequently overwritten), and makes sure to render a given function only once (to avoid the `(*current).onList10 redeclared in this block` type of errors).

Another approach could be to always clone nodes when optimizing, never assigning any reference, but that would result in code bloat (e.g. the same function body rendered multiple times under different names), and would possibly make the optimization code more complex.

### CODE REVIEW

**Comment by mna** [comment]
Looks like the tests < Go1.7 all fail because the `imports` package now uses the `context` package from the stdlib, which was introduced in Go 1.7. I can update the travis CI file in this PR if you'd like.

**Comment by breml** [comment]
@mna Thank you very much for the bug report #65 and this PR to resolve it.

I updated `.travis.yml` and `README.md` in regards to the Go < v1.7.

I also reviewed this PR and it makes sense to me. I only have two minor suggestions:

1. Because the bug only shows up, if `-optimize-grammar` is used, I suggest to run the tests with and without optimization (similar to how this is done in `examples/json`).
2. Because this test case handles an issue (#65) I suggest to place this test case in the directory `test/issue_65` (similar to how this was done for issues #1 and #18).

**Comment by mna** [comment]
Sounds good to me, I should be able to address your comments on Thursday. Thanks!

Martin

**Comment by mna** [comment]
@breml I addressed your comments, will let you take another look and merge (+squash if you want) if it looks good to you.

**Comment by breml** [comment]
@mna Thank you very much.

**Pull request merged**
