### PR TITLE
Add new predeclared identifiers

### PR DESCRIPTION
**Pull request by meyermarcel**
* Add max, min builtin functions to reserved words
* Remove duplicated reserved list
  * package `github.com/mna/pigeon/bootstrap` is used in pigeon.go
  * `make` regenerated pigeon.go

### CODE REVIEW

**Comment by meyermarcel** [comment]
`make` regenerated pigeon.go and I do not know if this is related to max, min. Is the new offset related to the 10 char long string `bootstrap.`?

**Comment by breml** [comment]
Hi @meyermarcel 
Thanks for your contribution. I prefer to keep the strict separation between the bootstrapping and the "regular" pigeon implementation and not having any dependencies between the two.

In regards to the additional reserved words `min` and `max`, I agree, that it does make sense to add them for the future. That being said, I wonder, if this could break backwards compatibility. But since these have been added already with Go 1.21 and we have now 1.23, I guess, this is in line with the defined **Release policy**.

In regards to `pigeon.go`, the changes are expected. This is fine for me.

**Comment by meyermarcel** [comment]
Thanks for your response. To keep the separation between bootstrapping and the "regular" pigeon I removed the last commits so only the reserved builtin functions are added.

**Comment by breml** [comment]
Thanks, I quickly checked https://go.dev/ref/spec#Predeclared_identifiers and found, that there are some more identifiers, that should be added, at least `any`, `comparable`, `clear`. May I ask you to double check the complete list?

**Comment by meyermarcel** [comment]
> Thanks, I quickly checked https://go.dev/ref/spec#Predeclared_identifiers and found, that there are some more identifiers, that should be added, at least `any`, `comparable`, `clear`. May I ask you to double check the complete list?

Good idea and sorry for my negligence. I will check it.

**Comment by meyermarcel** [comment]
> Thanks, I quickly checked https://go.dev/ref/spec#Predeclared_identifiers and found, that there are some more identifiers, that should be added, at least `any`, `comparable`, `clear`. May I ask you to double check the complete list?

Thanks for the hint. I added `any`, `comparable`, `clear` and changed the PR name.

**Review by breml — APPROVED** [review]
LGTM

**Pull request merged**
