### PR TITLE
Parse (and ignore) comments in code blocks

### PR DESCRIPTION
**Pull request by ear7h**
The following block of in a `.peg` file was yielding a parse error, presumably from the braces in the comments. My change adds a `Comment` clause (not sure if right word here) in the `Code` definition so they can be handled  appropriately.

```go
Value = "("_ val:Expr _ ")" {
	return val, nil
} / val:(ImLit / RealLit / IntLit) {
	fmt.Printf("Value: %T %v \n", val, val)
	return val, nil
// } / name:(Ident / "struct" / "class") "{" fields:{
// composite literal
} / val:Ident {
	return &Value{val.(string), Ident}, nil
}
```
the errror:
```text
parse error(s):
 grammar.peg:384:53 (7488): no match found, expected: "!", "#", "&", "'", "(", ".", "/*", "//", "[", "\"", "\n", "`", [ \t\r] or [\pL_]
```

### CODE REVIEW

**Comment by breml** [comment]
Hi @ear7h 
Thanks for your fix.
In order to get this into pegeon in a controlled way, I would like you to provide a minimal test case for the problem (see `test/issue_18` for an example), which can be executed before applying your change and after to verify your solution.
Additionally I updated pigeon to pass the tests at travisci again, so the tests in this PR should become green, once you have rebased it onto the master branch.

**Comment by ear7h** [comment]
@breml Thanks for pointing me to an example test, lmk if you'd like any more changes to the PR

**Comment by ear7h** [comment]
@breml I've pushed the fixes, could you please review it again?

**Comment by breml** [comment]
@ear7h Thanks for the updated PR. I will try to have a look at this soon.

**Comment by breml** [comment]
LGTM

@ear7h Thanks for your PR.

**Pull request merged**
