### PR TITLE
Implementation of labeled failures

### PR DESCRIPTION
**Pull request by breml**
This commit adds two new expression types to the PEG syntax:
1) `%{label}` is used to throw an exception, which is possibly recovered
2) `expr //{label1, label2, labeln} recoveryExpr` allows to execute a recovery expression
in case a matching label is thrown.

Syntax for labeled failures is based on [lpeglabel](https://github.com/sqmedeiros/lpeglabel),
which is the reference implementation for the labeled failures feature,
proposed in the paper: [Error Reporting in Parsing Expression Grammars](https://arxiv.org/pdf/1405.6646v3.pdf)

### CODE REVIEW

**Comment by breml** [comment]
@sqmedeiros I am sorry to bother you, but I thought, you might be interested in this PR. Pigeon is a PEG based parser generator for Go. This PR implements the labeled failures functionality, which is described in your [paper](https://arxiv.org/pdf/1405.6646v3.pdf) as well as implemented in your "reference" implementation [lpeglabel](https://github.com/sqmedeiros/lpeglabel).

I would appreciate, if you would have a look at the implementation and give me your opinion. Especially I am interested to know, what you think about the way, the `throw` and the `recovery` operators are implemented. In this implementation, the [recovery](https://github.com/mna/pigeon/pull/39/files#diff-288fa6d159a3e33479b4e95cd813fd4fR1005) operation adds the label and the recovery (alternative) operation to a stack. The [throw](https://github.com/mna/pigeon/pull/39/files#diff-288fa6d159a3e33479b4e95cd813fd4fR1060) operation checks the stack, if the thrown label has a recovery operation attached. If this is the case, this operation is executed instead.

I also implemented your PEG syntax for the `throw` and the `recovery` operations and verified the functionality with a [test cases](https://github.com/mna/pigeon/pull/39/files#diff-93e43b04448e4c205f4fe870f59ef6d9) of yours.

**Comment by sqmedeiros** [comment]
Hi, @breml .

I'm glad to know that you implemented labeled failures.

The implementation seems fine. My implementation is similar to yours, I have also used a stack in this way. This implementation allows to define a local scope to labels. 

One thing that seems different is that your function `parseThrowExpr` returns `nil, false` when a label **lab** does not have a recovery operation. In case of LPegLabel, this function would return something as `nil, lab`, because **lab** could be used after to produce a better error message. Sometimes a user may implement just error reporting, without error recovery.

I am wondering about providing a slightly different implementation of LPegLabel, where the user specifies a map with labels and its respective recovery operations. By doing this, the impact would be: the recovery operator (**//**) will not be used (or it would just overwrite the associated table entry), the stack would not be necessary, it would not be possible to define a local scope to labels.

**Comment by breml** [comment]
Hi @sqmedeiros,
Thanks for your quick response. I really appreciate.
You are right, in `parseThrowExpr` I am returning `nil, false`. This is also the case for the other expressions if they fail and it keeps the functionality the same as if there were no `throw` at all.

The *farthest failure* (also based on the suggestions in your paper) is only tracked in the matchers (`litMatcher`, `charClassMatcher` and `anyMatcher`), which worked well in the past and I do not expect this to change with the two new expressions (`recover` and `throw`) as I assume, that some matching had failed before at the same parsing position, before the label was thrown.

Your idea about the different implementation is interesting. I understand, how you would implement it as well as the simplification the the grammar. Do you also have some information about how this would impact the possible use cases. Currently I see two use cases for the `throw`/`recover` expressions (which are in a way connected).

1.Better error reporting during parsing
2. Robust parsing

What are your thoughts or experiences on this?

**Comment by sqmedeiros** [comment]
Yes, @breml, the farthest failure tracking should still work well.
The change I mentioned would not impact the two use cases you listed. I think the main difference is that we will have recovery expressions (defined in a map that will be accessed by throw), but not the recovery operator.
There is also the labeled ordered choice */{}*, which is mentioned in https://arxiv.org/pdf/1405.6646v3.pdf, which may also be used for error reporting/recovery, but I think the recovery operator is more appropriate for this task. The labeled ordered choice seems more useful as a prediction mechanism, as shown in Section 6 of the paper, that uses */{}* to simulate the prediction mechanism of ANTLR.

**Comment by breml** [comment]
@sqmedeiros Thank you very much for your clarifications. So I will stick to the current implementation.

@mna, @jlozano, @goller As all of you have reacted to or have been involved during the development of this PR, I reach out to you with the following question:

This feature is also especially useful to implement more error resistant / robust parsers. This leads to the situation, where the parsing (based on a robust grammar) is actually successful (due to the recovery mechanisms) but still there are errors returned from the parser. This makes the Go idiom for error checking a little bit awkward. Consider this:

With a robust grammar ([example](https://github.com/mna/pigeon/pull/39/files#diff-c1eda9bb9e5023fbd9cd27b13afe2bcdR31)), the below code would return errors (like [here](https://github.com/mna/pigeon/pull/39/files#diff-93e43b04448e4c205f4fe870f59ef6d9R24) but still the returned [value](https://github.com/mna/pigeon/pull/39/files#diff-93e43b04448e4c205f4fe870f59ef6d9R23) from the parser would be valid.

```
got, err := Parse("", input)
if err != nil {
    log.Fatal(err)
}
```

Therefore I am asking myself, what would be the right / idiomatic way to return in those situations. The parser actually knows, if it was [successful](https://github.com/mna/pigeon/blob/master/builder/static_code.go#L583), but this information is currently [not returned](https://github.com/mna/pigeon/blob/master/builder/static_code.go#L610) to the user.

I currently see two possibilities:

1. Encode the information, if the parser was successful in the returned error
2. Change the function signature for all the `Parse` functions to return an additional bool, indicating if the parsing was successful (`func Parse(filename string, b []byte, opts ...Option) (interface{}, bool, error) {`

What do you think?

**Comment by jlozano** [comment]
@breml sorry for the delay responding to this. 

This issue also occurs in the go parser, https://github.com/golang/go/blob/master/src/go/parser/interface.go#L78.

I vote for option 1.

Reasoning:
a) If we change the return signature of `Parse` and `ParseReader` to `(interface{}, bool, error)` then I think that it  is unclear to the client how they should determine if parsing was successful, do they check the `bool` and the `error`, just the `error` or just the `bool` ?
b) I think from the client perspective we have the following behavior:
`err == nil` -- result is definitely valid, everything is fine.
` err != nil` -- may have gotten a partial result, investigate the errors to determine whether or not the results are suitable for your purpose.
From the perspective of robust parsing, this seems correct, since in the first case the client knows for certain that the input was syntactically valid and in the second case the client knows that the input was *not* syntactically valid and it is up to them to determine if the partial results suit their needs. I think it is important to note that even in the case of robust parsing we only consider the result as *valid* if there were *no* syntax errors at all, in the case that there were syntax errors we usually consider the result as only "partially valid" or "approximately valid".

**Comment by breml** [comment]
@jlozano Thanks for your feedback. Your reasoning makes sense to me. Given the two options above, I am also in favor of option 1 (which is also the way it is currently implemented), especially because I do not like to change the current API in a breaking way.

I thought about a third option, which is to not change the current functions, but to add new ones with the extended signature. That is:
* `func ParseWithResult(filename string, b []byte, opts ...Option) (interface{}, bool, error)`
* `func ParseFileWithResult(filename string, opts ...Option) (i interface{}, bool, err error)`
* `func ParseReaderWithResult(filename string, r io.Reader, opts ...Option) (interface{}, bool, error)`

This of course would also imply, that the function signature of `func (p *parser) parse(g *grammar) (val interface{}, err error) {` would change, because the result of the parsing would be returned, but is not part of the official / exposed API.

I was kind of thinking in the direction where the parser not only validates some input syntactically. Then the parser could well return something like warnings, where the parsing is ok, the returned is ok but there are still some issues with the input (e.g. deprecation warnings).

If someone comes up with some really good arguments, why he needs the actual result of the parsing, this could be the way, how this is achieved.

So I think, we are ready to merge this one, even though the examples will slightly change, when #40 will be implemented.

**Pull request merged**
