### PR TITLE
Add globalStore

### PR DESCRIPTION
**Pull request by breml**
The "globalStore" field is a global store of type "map[string]interface{}",
which allows to store arbritary values, which are available in action and
predicate code blocks for read as well as write access.

see `test/global_store` for example usage

Possible fix for #8 
Could be used to store for farthest error as solution for #18

### CODE REVIEW

**Comment by mmussomele** [comment]
@breml this would be super useful for me, is it ready for use?

**Comment by breml** [comment]
@mmussomele Thanks for your feedback. I think it is more or less ready to be used.
Could you give it a try and provide feedback, if it works for you?
I did not yet merge it, because I do not use it yet. And no other usere has really requested it. My initial use case was to use it for the recording of the farthest failure position. But then I decided to build in this feature natively into pigeon.
I have a parser project, where it could be of use, but this one is on hold.

**Comment by mmussomele** [comment]
@breml I'm using it right now, haven't noticed any issues with it and it works like I'd expect. FWIW I'm using it to collect comments from source files.

**Comment by breml** [comment]
@mmussomele Thanks for your feedback. I will merge this PR.

**Pull request merged**
