### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by xrstf**
I stumbled upon the "expresssions" typo in the generated code of my language and then ran the spellchecker on Pigeon, finding a few other minor typos.

### CODE REVIEW

**Review by breml — APPROVED** [review]
LGTM, I just updated the generated code.

Thanks for the contribution.

**Comment by xrstf** [comment]
While I have your attention: thank you for pigeon, it made building my own language such a breeze that I had to read little to no documentation at all, besides the JSON example. And everything _just worked_.

Thank you for building Pigeon.

**Comment by breml** [comment]
@xrstf Thanks for your kind words. I happily pass on the compliment further to @mna who laid the foundation.

**Comment by mna** [comment]
@xrstf Thanks for the kind words, and many thanks to @breml for your great work on this and taking this project to the next level!

**Pull request merged**
